version: '3.8'

services:
  coordinator:
    build: ./agents/coordinator_agent
    environment:
      - GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}
      - GCP_REGION=${GCP_REGION}
    env_file:
      - .env
